# Generated by Django 3.2.4 on 2021-06-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_medic',
            field=models.BooleanField(default=False),
        ),
    ]
